name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate top languages card 
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&count_private=true&layout=compact&theme=dark&bg_color=00000000&text_color=EBEBEB&title_color=EBEBEB&langs_count=10&size_weight=0.5&count_weight=0.5&card_width=600
          path: profile/top-langs.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate top languages card test 600 6
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&card_width=600&langs_count=6
          path: profile/top-langs-test-600-6.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate top languages card test 600 10
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&card_width=600&langs_count=10
          path: profile/top-langs-test-600-10.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate top languages card test 400 6
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&card_width=400&langs_count=6
          path: profile/top-langs-test-400-6.svg
          token: ${{ secrets.GH_PAT }}

      - name: Generate top languages card test 400 10
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&card_width=400&langs_count=10
          path: profile/top-langs-test-400-10.svg
          token: ${{ secrets.GH_PAT }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
